# handlers/invitation.py
from telegram import Update, ChatMember, ChatMemberUpdated
from telegram.ext import ContextTypes
from telegram.error import TelegramError
from database import Session, User
from models.referral import Referral
from services import economy

# Config: How many points per invite?
INVITE_REWARD_POINTS = 20

async def generate_invite_link(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Command: 专属链接
    Generates a unique invite link for the user in the current group.
    """
    chat = update.effective_chat
    user = update.effective_user

    # 1. Ensure this is a group
    if chat.type == 'private':
        await update.message.reply_text("⚠️ 请在群组中使用此命令，以生成该群的专属邀请链接。")
        return

    # 2. Try to create the link
    try:
        # Create a link that doesn't expire quickly, but you can adjust limits if needed
        # We name it so we can easily identify it in the management menu if needed
        invite_link = await context.bot.create_chat_invite_link(
            chat_id=chat.id,
            name=f"{user.first_name} ({user.id})",
            creates_join_request=False # Direct join
        )
        
        await update.message.reply_text(
            f"✅ {user.mention_html()} 的专属邀请链接:\n\n"
            f"{invite_link.invite_link}\n\n"
            f"🎉 邀请新用户加入，每位奖励 {INVITE_REWARD_POINTS} 积分!",
            parse_mode='HTML'
        )
        
    except TelegramError as e:
        await update.message.reply_text("❌ 生成失败: 机器人需要管理员权限 (必须拥有 '邀请用户' 权限).")
        print(f"Invite Link Error: {e}")

async def track_join_event(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Detects when a user joins via an invite link.
    """
    result = _extract_status_change(update.chat_member)
    if result is None:
        return

    was_member, is_member = result
    
    # We only care if they are JOINING (Not member -> Member)
    if was_member or not is_member:
        return

    # Get the invite link used
    # Note: invite_link is only available if the user joined via a link generated by the bot
    new_member = update.chat_member.new_chat_member
    invite_link = update.chat_member.invite_link

    if not invite_link or not invite_link.creator:
        return

    inviter = invite_link.creator
    joined_user = new_member.user

    # Prevent self-invite (shouldn't happen normally, but good to be safe)
    if inviter.id == joined_user.id:
        return

    # DATABASE CHECK
    session = Session()
    try:
        # Check if this referral already exists
        exists = session.query(Referral).filter_by(
            inviter_id=inviter.id, 
            invited_user_id=joined_user.id
        ).first()

        if exists:
            print(f"Duplicate referral: {inviter.id} -> {joined_user.id}")
            return
        
        # New Referral!
        # 1. Record it
        new_ref = Referral(inviter_id=inviter.id, invited_user_id=joined_user.id)
        session.add(new_ref)
        session.commit()
        
        # 2. Add Points to Inviter
        # (We use the economy service to ensure user exists)
        economy.get_or_create_user(inviter.id, inviter.username or "Unknown", inviter.first_name)
        economy.add_points(inviter.id, float(INVITE_REWARD_POINTS))

        # 3. Notify
        await context.bot.send_message(
            chat_id=update.effective_chat.id,
            text=f"📢 邀请成功!\n"
                 f"🎉 {inviter.mention_html()} 邀请了 {joined_user.mention_html()}!\n"
                 f"💰 获得奖励: {INVITE_REWARD_POINTS} 积分",
            parse_mode='HTML'
        )

    except Exception as e:
        print(f"Referral Error: {e}")
    finally:
        session.close()

def _extract_status_change(chat_member_update: ChatMemberUpdated):
    """
    Helper to determine if the user joined or left.
    Returns (was_member, is_member) or None
    """
    status_change = chat_member_update.difference().get("status")
    old_is_member, new_is_member = chat_member_update.difference().get("is_member", (None, None))

    if status_change is None:
        return None

    old_status, new_status = status_change
    
    was_member = old_status in [
        ChatMember.MEMBER,
        ChatMember.OWNER,
        ChatMember.ADMINISTRATOR,
    ] or (old_status == ChatMember.RESTRICTED and old_is_member is True)

    is_member = new_status in [
        ChatMember.MEMBER,
        ChatMember.OWNER,
        ChatMember.ADMINISTRATOR,
    ] or (new_status == ChatMember.RESTRICTED and new_is_member is True)

    return was_member, is_member